### ISSUE TITLE
Proposal: add option to customize casing for de-/serialization when using "with-serde"

### ISSUE THREAD

**Issue by bachmannscode** [zbrox/iso_currency#23]
Problem statement: I want to parse an API where the casing convention doesn't match the one in the crate.

A suggested fix: Serde already has [attributes](https://serde.rs/variant-attrs.html#rename_all) to customize casing. They would only need to be exposed in the crate.

**Comment by zbrox** [comment]
Hey, sorry for the delayed response. 

I can see the value in this. I am just not sure what would be the optimal way to achieve this. The `Currency` enum is generated on build time. At first glance, in order to know which casing convention the user would prefer we would have to add a bunch of mutually exclusive features for each of the possible values of serde's `rename_all` (which are "lowercase", "UPPERCASE", "PascalCase", "camelCase", "snake_case", "SCREAMING_SNAKE_CASE", "kebab-case", "SCREAMING-KEBAB-CASE"). I'm also a bit unsure about having features modify behavior in such a way. It feels not exactly in the spirit of the purpose of Cargo features. 

But in any case, I'm open to implementation ideas on how to achieve this, maybe there's a better way.
